name: Pull Request Tests
on:
  pull_request:
    branches:
      - main
jobs:
    success:
      name: Run successfully
      runs-on: ubuntu-latest
      steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Run
        run: sh ./run.sh
    error:
      name: Run with error
      runs-on: ubuntu-latest
      steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Run
        run: sh ./run.sh err
